---

- name: Read join command from master
  ansible.builtin.slurp:
    src: /tmp/kube_join.txt
  register: joinfile

- name: Extract kubeadm join command
  ansible.builtin.set_fact:
    join_cmd: "{{ joinfile.content | b64decode | regex_search('kubeadm join.*') }}"


# kubeadm creates /etc/kubernetes/kubelet.conf when a node successfully joins
- name: Join worker to cluster
  ansible.builtin.command: "sudo {{ join_cmd }}"
  args:
    creates: /etc/kubernetes/kubelet.conf

