
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>K8s Demo</title>
      </head>
      <body>
        <h1>Hello from Kubernetes!</h1>
        <p>Hi I'm Dennis hope you enjoy the process of learning K8s.</p>
      </body>
      </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-html
