---
- name: Check if user exists
  ansible.builtin.getent:
    database: passwd
    key: petops
  register: user_exists

- name: Create non-root user
  ansible.builtin.user:
    name: petops
    groups: sudo
    append: yes
    shell: /bin/bash
    create_home: yes
  when: user_exists.failed is defined and user_exists.failed

- debug:
    msg: "User 'petops' created or already exists."
